# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('sub_title', models.CharField(max_length=128)),
                ('images', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('second_hand', models.BooleanField(default=False)),
                ('sales', models.BooleanField(default=False)),
                ('support_send', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('off', 'Off the shelf'), ('on', 'In the sale of'), ('empty', 'Commodity is empty')], default='on', help_text='', max_length=8, verbose_name='On sale')),
                ('detail', models.CharField(max_length=4096)),
                ('parameter', models.CharField(max_length=4096)),
                ('trans_condition', models.CharField(max_length=256)),
                ('send_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trans_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'commodity',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CommResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=1024)),
                ('image', models.CharField(max_length=128)),
                ('score', models.IntegerField(choices=[(0, 'lowest'), (1, 'score 1'), (2, 'score 2'), (3, 'score 3'), (4, 'score 4'), (5, 'higest')], default=5, help_text='')),
                ('anonymous', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_response', to='main.User')),
                ('comm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.Commodity')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_list', to='shop.CommResponse')),
            ],
            options={
                'db_table': 'comm_response',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Ordered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('start', ''), ('payed', ''), ('sending', ''), ('cancel', 'canceled'), ('received', 'received'), ('finish', 'finished')], default='start', max_length=8)),
                ('pay_way', models.CharField(choices=[('offline', ''), ('online', 'pay on the line')], default='offline', max_length=8)),
                ('commented', models.BooleanField(default=False)),
                ('contract_number', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('sub_title', models.CharField(max_length=128)),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('send_date', models.DateTimeField(default=None, null=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(default=1)),
                ('origin_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_off_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trans_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comm_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Commodity')),
            ],
            options={
                'db_table': 'ordered',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('logo', models.CharField(max_length=128)),
                ('serial_number', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=16)),
                ('charge_indentity', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=128)),
                ('shop_type', models.CharField(choices=[('common', 'Common shop'), ('star', 'Star shop')], default='common', help_text='', max_length=8, verbose_name='common shop or start shop')),
                ('zip_code', models.CharField(max_length=6)),
                ('pos', models.CharField(max_length=128)),
                ('level', models.IntegerField(default=0, help_text='')),
                ('status', models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status')),
            ],
            options={
                'db_table': 'shop',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status')),
                ('parent_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='shop.ShopCategory')),
            ],
            options={
                'db_table': 'comm_category',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserShopLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=0, help_text='')),
                ('privilege', models.CharField(choices=[('owner', 'owner'), ('admin', 'shop adminitrator'), ('user', 'common user')], default='user', max_length=8)),
                ('locked', models.BooleanField(default=False)),
                ('shop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shop.Shop')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_level', to='main.User')),
            ],
            options={
                'db_table': 'shop_user_level',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_shop', to='shop.ShopCategory'),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='main.User'),
        ),
        migrations.AddField(
            model_name='ordered',
            name='shop_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='ordered',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.User'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commodities', to='shop.ShopCategory'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='shop.Shop'),
        ),
    ]
