# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171202_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='status',
            field=models.CharField(choices=[('off', 'Off the shelf'), ('on', 'In the sale of'), ('empty', 'Commodity is empty')], default='on', help_text='', max_length=8, verbose_name='On sale'),
        ),
        migrations.AlterField(
            model_name='commresponse',
            name='score',
            field=models.IntegerField(choices=[(0, 'lowest'), (1, 'score 1'), (2, 'score 2'), (3, 'score 3'), (4, 'score 4'), (5, 'higest')], default=5, help_text=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='level',
            field=models.IntegerField(default=0, help_text=''),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(choices=[('common', 'Common shop'), ('star', 'Star shop')], default='common', help_text='', max_length=8, verbose_name='common shop or start shop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='status',
            field=models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='usershoplevel',
            name='level',
            field=models.IntegerField(default=0, help_text=''),
        ),
    ]
