# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=4096)),
                ('images', models.CharField(max_length=128)),
                ('anonymous', models.BooleanField(default=False)),
                ('prohibit_res', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main.User')),
            ],
            options={
                'db_table': 'bbs_article',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='BBSCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status')),
                ('parent_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='bbs.BBSCategory')),
            ],
            options={
                'db_table': 'bbs_category',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=4096)),
                ('anonymous', models.BooleanField(default=False)),
                ('prohibit_res', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='main.User')),
                ('origin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='bbs.Article')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_list', to='bbs.ResponseModel')),
            ],
            options={
                'db_table': 'bbs_response',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserBoardLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField(default=0, help_text='')),
                ('privilege', models.CharField(choices=[('super', 'super administrator'), ('admin', 'board adminitrator'), ('user', 'common user')], default='user', max_length=8)),
                ('locked', models.BooleanField(default=False)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bbs.BBSCategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_level', to='main.User')),
            ],
            options={
                'db_table': 'bbs_user_level',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='bbs.BBSCategory'),
        ),
    ]
