# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20171202_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='bbscategory',
            name='status',
            field=models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='userboardlevel',
            name='level',
            field=models.IntegerField(default=0, help_text=''),
        ),
    ]
