# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20171209_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='res_num',
            field=models.IntegerField(default=0, help_text=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='bbscategory',
            name='status',
            field=models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='parent_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response_list', to='bbs.ResponseModel'),
        ),
        migrations.AlterField(
            model_name='responsemodel',
            name='res_num',
            field=models.IntegerField(default=0, help_text=''),
        ),
        migrations.AlterField(
            model_name='userboardlevel',
            name='level',
            field=models.IntegerField(default=0, help_text=''),
        ),
    ]
