# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('logo', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=16, verbose_name='Current Status')),
            ],
            options={
                'db_table': 'category',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('logo', models.CharField(max_length=128)),
                ('passwd', models.CharField(max_length=256)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'Female')], default='m', help_text='', max_length=1, verbose_name='male or female')),
                ('birth', models.DateTimeField()),
                ('wx_id', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=16)),
                ('identity', models.CharField(max_length=18)),
                ('nick', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('folder', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=64)),
                ('sign', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'In Using'), ('delete', 'Deleted'), ('lock', 'Only view, cannot edit it')], default='active', help_text='', max_length=8, verbose_name='Current Status')),
            ],
            options={
                'db_table': 'user',
                'ordering': ('id',),
            },
        ),
    ]
